sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password:

  alioss:
    endPoint: oss-cn-beijing.aliyuncs.com
    bucketName: freetrial
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
#    database 0不同的数据库，默认生成了16个库

  wechat:
    appid: wxa3a75c3ef5b35206
    secret: cb1060c911fa0e3031200024829f99d4